version: "3.6"

services:
  caddy:
    image: berml/caddy
    ports:
    - 80:80
    environment:
    - EASYCD_DOMAIN=${EASYCD_DOMAIN:-localhost}
    - EASYCD_SCHEME=${EASYCD_SCHEME:-http}

  portainer:
    image: portainer/portainer:1.20.2
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data

  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - pgadmin:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=${EASYCD_USER:-easycd}
    - PGADMIN_DEFAULT_PASSWORD=${EASYCD_PASSWORD:-easycd}

  gitea:
    image: gitea/gitea:1.8
    volumes:
    - gitea:/data
    environment:
    - RUN_MODE=prod
    - ROOT_URL=${EASYCD_SCHEME:-http}://gitea.${EASYCD_DOMAIN:-localhost}
    - DB_TYPE=postgres
    - DB_HOST=gitea-postgres:5432
    - DB_USER=${EASYCD_USER:-easycd}
    - DB_PASSWD=${EASYCD_PASSWORD:-easycd}
    - DB_NAME=gitea
    - SSH_DOMAIN=${EASYCD_DOMAIN:-localhost}
    - SSH_PORT=2222
    ports:
    - 2222:22

  gitea-postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=${EASYCD_USER:-easycd}
    - POSTGRES_PASSWORD=${EASYCD_PASSWORD:-easycd}
    - POSTGRES_DB=gitea
    volumes:
    - gitea-postgres:/var/lib/postgresql/data

  drone:
    image: drone/drone:1.0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - drone:/data
    environment:
    - DRONE_GITEA_SERVER=http://gitea:3000 #${EASYCD_SCHEME:-http}://gitea.${EASYCD_DOMAIN:-localhost}
    - DRONE_GIT_ALWAYS_AUTH=true
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_SERVER_HOST=drone.${EASYCD_DOMAIN:-localhost}
    - DRONE_SERVER_PROTO=${EASYCD_SCHEME:-http}
    - DRONE_TLS_AUTOCERT=false
    - DRONE_DATABASE_DRIVER=postgres
    - DRONE_DATABASE_DATASOURCE=postgres://${EASYCD_USER:-easycd}:${EASYCD_PASSWORD:-easycd}@drone-postgres:5432/drone?sslmode=disable

  drone-postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=${EASYCD_USER:-easycd}
    - POSTGRES_PASSWORD=${EASYCD_PASSWORD:-easycd}
    - POSTGRES_DB=drone
    volumes:
    - drone-postgres:/var/lib/postgresql/data

  # nexus:
  #   image: sonatype/nexus3:3.15.2
  #   volumes:
  #   - nexus:/nexus-data

volumes:
  gitea:
  gitea-postgres:
  portainer:
  drone:
  drone-postgres:
  pgadmin:
  # nexus: